"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,useGLTF,Line,Html} from "@react-three/drei";
import {Suspense,useEffect,useMemo,useRef,useState} from "react";
import * as THREE from "three";
import {motion,useMotionValueEvent,useScroll} from "framer-motion";
import {Activity,BatteryCharging,Bell,ChevronRight,CircleAlert,Fuel,Gauge,Pause,Play,Plus,Radio,Rotate3D,ShieldAlert,Trash2,Truck,Zap} from "lucide-react";

function Loader(){return <div className="absolute inset-0 grid place-items-center bg-[#071916]"><div className="w-52 space-y-3"><div className="h-2 animate-pulse rounded-full bg-emerald-400/20"><div className="h-full w-2/3 rounded-full bg-emerald-400"/></div><p className="text-center text-[9px] font-black uppercase tracking-[.2em] text-emerald-300">Loading spatial model</p></div></div>}

function TrackerModel({explode}:{explode:number}){
 const gltf=useGLTF("/gps-tracker.glb");
 const group=useRef<THREE.Group>(null);
 const parts=useMemo(()=>gltf.scene.children.map((c,i)=>({obj:c.clone() as THREE.Object3D,base:c.position.clone(),dir:new THREE.Vector3((i%2?1:-1)*(1+i*.08),i*.32-1,(i%3-1)*.7)})),[gltf]);
 useFrame((state,dt)=>{if(group.current){group.current.rotation.y+=dt*.12;group.current.rotation.x=THREE.MathUtils.lerp(group.current.rotation.x,state.pointer.y*.12,.05)} parts.forEach(p=>p.obj.position.lerp(p.base.clone().addScaledVector(p.dir,explode),.08))});
 return <group ref={group} scale={1.05}>{parts.map((p,i)=><primitive key={i} object={p.obj}/>)}</group>
}
useGLTF.preload("/gps-tracker.glb");

export function HardwareExplorer(){
 const ref=useRef<HTMLElement>(null); const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]}); const [explode,setExplode]=useState(0);
 useMotionValueEvent(scrollYProgress,"change",v=>setExplode(Math.max(0,Math.min(1,(v-.2)*2))));
 const labels=[["Case shell","Impact-resistant enclosure"],["4G antenna","Reliable data transmission"],["PCB core","Precision fleet telemetry"],["SIM slot","Secure network identity"],["Battery","Backup power continuity"]];
 return <section ref={ref} className="relative overflow-hidden bg-[#041310] px-5 py-28 text-white sm:px-[5vw] lg:py-36" id="hardware-3d">
  <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(16,185,129,.22),_transparent_58%)] opacity-80"/>
  <div className="mx-auto grid max-w-[1300px] items-center gap-12 lg:grid-cols-[.82fr_1.18fr]">
   <div className="relative z-10"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-emerald-300"><span className="relative flex h-3 w-3"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-60"/><span className="relative inline-flex h-3 w-3 rounded-full bg-emerald-500 shadow-[0_0_15px_#10b981]"/></span> Interactive 3D hardware</div><h2 className="mt-6 text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Built strong.<br/><span className="text-emerald-300">Revealed layer by layer.</span></h2><p className="mt-6 max-w-lg text-sm leading-7 text-slate-400">Scroll to separate the tracker into its functional layers. Drag the model for a full 360° inspection of the enclosure, antenna, PCB, SIM slot and backup battery.</p>
   <div className="mt-8 grid gap-2 sm:grid-cols-2">{labels.map((x,i)=><motion.div key={x[0]} animate={{opacity:explode>i*.14?.95:.35,x:explode>i*.14?0:-8}} className="rounded-xl border border-emerald-400/15 bg-slate-900/40 p-3 backdrop-blur-xl"><b className="text-xs">{x[0]}</b><p className="mt-1 text-[9px] text-slate-500">{x[1]}</p></motion.div>)}</div></div>
   <div className="relative h-[520px] overflow-hidden rounded-[30px] border border-emerald-400/20 bg-slate-950/60 shadow-[0_8px_55px_rgba(0,0,0,.55)] backdrop-blur-2xl transform-gpu will-change-transform">
    <Suspense fallback={<Loader/>}><Canvas camera={{position:[6,4.5,7],fov:40}} dpr={[1,1.7]} gl={{antialias:true,powerPreference:"high-performance"}}><ambientLight intensity={1.1}/><directionalLight position={[5,7,5]} intensity={3} color="#baffdb"/><pointLight position={[-4,2,-3]} intensity={8} color="#10b981"/><TrackerModel explode={explode*1.9}/><OrbitControls enablePan={false} minDistance={5} maxDistance={11} autoRotate={explode<.15} autoRotateSpeed={.7}/></Canvas></Suspense>
    <div className="pointer-events-none absolute bottom-5 left-5 flex items-center gap-2 rounded-full border border-white/10 bg-black/35 px-4 py-2 text-[9px] font-bold text-slate-300 backdrop-blur-xl"><Rotate3D className="h-4 w-4 text-emerald-300"/> Drag to rotate · Scroll to explode</div>
   </div>
  </div>
 </section>
}

function Arc({from,to,color="#62eaa5"}:{from:[number,number,number],to:[number,number,number],color?:string}){
 const mid=new THREE.Vector3(...from).add(new THREE.Vector3(...to)).multiplyScalar(.5).normalize().multiplyScalar(2.8);
 const curve=new THREE.QuadraticBezierCurve3(new THREE.Vector3(...from),mid,new THREE.Vector3(...to)); const pts=curve.getPoints(40);
 return <Line points={pts} color={color} lineWidth={1.5} transparent opacity={.75} dashed dashScale={5} dashSize={.15} gapSize={.1}/>;
}
function Globe(){
 const ref=useRef<THREE.Group>(null); useFrame((_,dt)=>{if(ref.current)ref.current.rotation.y+=dt*.045});
 const cities:[[number,number,number],[number,number,number],string][]=[[[1.1,.9,1.25],[0,2.65,0],"Accra"],[[-1.25,.35,1.3],[0,2.65,0],"Lagos"],[[1.35,-.55,-1.05],[0,2.65,0],"Dubai"],[[-.6,1.45,-.85],[0,2.65,0],"Toronto"]];
 return <group ref={ref}><mesh><sphereGeometry args={[1.8,64,64]}/><meshStandardMaterial color="#08211b" emissive="#063c2b" emissiveIntensity={.8} roughness={.7} wireframe/></mesh><mesh><sphereGeometry args={[1.78,48,48]}/><meshPhysicalMaterial color="#0b3529" transparent opacity={.56} roughness={.55}/></mesh>{cities.map((c,i)=><group key={i}><mesh position={c[0]}><sphereGeometry args={[.065,16,16]}/><meshBasicMaterial color={i===2?"#ffad62":"#61f1aa"}/></mesh><Arc from={c[0]} to={c[1]} color={i===2?"#ffad62":"#61f1aa"}/></group>)}<group position={[0,2.65,0]}><mesh><octahedronGeometry args={[.22,0]}/><meshStandardMaterial color="#dffff0" emissive="#35e695" emissiveIntensity={2}/></mesh><Html center distanceFactor={9}><div className="whitespace-nowrap rounded-full border border-emerald-300/20 bg-black/70 px-3 py-1 text-[8px] font-black text-emerald-200 backdrop-blur-xl">LAMBODRA CLOUD</div></Html></group></group>
}
export function SpatialGlobe(){
 return <section className="relative overflow-hidden bg-[#071916] px-5 py-24 text-white sm:px-[5vw] lg:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_45%,rgba(16,185,129,.18),transparent_42%)]"/>
  <div className="mx-auto grid max-w-[1300px] items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="relative z-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-300">Spatial fleet twin</p><h2 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.055em] sm:text-7xl">One cloud.<br/>Every moving asset.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-slate-400">Glowing telemetry arcs connect active fleet markers to Lambodra’s secure cloud node, translating continuous GPS signals into a single operational picture.</p><div className="mt-8 flex gap-7"><div><b className="text-2xl text-emerald-300">24</b><p className="text-[9px] uppercase tracking-wider text-slate-500">Live vehicles</p></div><div><b className="text-2xl">4 sec</b><p className="text-[9px] uppercase tracking-wider text-slate-500">Update interval</p></div><div><b className="text-2xl">99.9%</b><p className="text-[9px] uppercase tracking-wider text-slate-500">Signal uptime</p></div></div></div>
  <div className="relative h-[520px] rounded-[30px] border border-emerald-400/20 bg-slate-950/40 shadow-[0_8px_55px_rgba(0,0,0,.45)] backdrop-blur-2xl"><Suspense fallback={<Loader/>}><Canvas camera={{position:[0,1.2,7],fov:42}} dpr={[1,1.6]} gl={{powerPreference:"high-performance"}}><ambientLight intensity={.8}/><pointLight position={[2,4,5]} intensity={8} color="#5ff0a8"/><Globe/><OrbitControls enablePan={false} enableZoom={false} autoRotate autoRotateSpeed={.32}/></Canvas></Suspense><div className="absolute right-5 top-5 rounded-xl border border-white/10 bg-slate-900/40 p-3 text-[9px] backdrop-blur-2xl"><span className="flex items-center gap-2 font-black text-emerald-300"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400"/><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500"/></span> LIVE TELEMETRY</span></div></div></div>
 </section>
}

function Truck3D({progress}:{progress:number}){
 const g=useRef<THREE.Group>(null); useFrame((state)=>{if(g.current){const a=progress*Math.PI*1.7;g.current.position.set(Math.sin(a)*2.2,-.5,Math.cos(a)*1.25);g.current.rotation.y=a;g.current.position.y+=Math.sin(state.clock.elapsedTime*5)*.015}});
 return <group ref={g}><mesh position={[0,.35,0]}><boxGeometry args={[1.35,.65,.75]}/><meshStandardMaterial color="#58e7a0" metalness={.25}/></mesh><mesh position={[-.7,.22,0]}><boxGeometry args={[.5,.48,.76]}/><meshStandardMaterial color="#d9ece1" metalness={.3}/></mesh>{[-.48,.48].flatMap(x=>[-.43,.43].map((z,i)=><mesh key={x+""+i} position={[x,0,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.16,.16,.12,18]}/><meshStandardMaterial color="#101716"/></mesh>))}</group>
}
export function VehicleJourney(){
 const ref=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const[p,setP]=useState(0);useMotionValueEvent(scrollYProgress,"change",v=>setP(v));
 return <section ref={ref} className="bg-[#eef3ee] px-5 py-24 sm:px-[5vw] lg:py-32"><div className="mx-auto max-w-[1300px]"><div className="mb-10 max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-700">Scroll-driven vehicle journey</p><h2 className="mt-5 text-5xl font-black leading-[.96] tracking-[-.055em] sm:text-7xl">Follow the data from ignition to insight.</h2></div><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="relative h-[520px] overflow-hidden rounded-[28px] bg-[#061512] shadow-2xl transform-gpu will-change-transform"><Canvas camera={{position:[0,4.8,7.5],fov:44}} dpr={[1,1.5]}><ambientLight intensity={1}/><directionalLight position={[3,6,4]} intensity={4} color="#baffdc"/><gridHelper args={[12,20,"#245c49","#102e24"]}/><Truck3D progress={p}/><OrbitControls enableZoom={false} enablePan={false} autoRotate autoRotateSpeed={.18}/></Canvas><div className="absolute bottom-5 left-5 right-5 h-1 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full bg-emerald-400" style={{width:(p*100)+"%"}}/></div></div><div className="space-y-3">{[["01","Ignition detected","Tracker wakes and verifies device health."],["02","Signal acquired","GPS coordinates lock within seconds."],["03","Cloud synchronised","Encrypted telemetry reaches the platform."],["04","Fleet insight ready","Routes, alerts and health become actionable."]].map((x,i)=><div key={x[0]} className={"rounded-2xl border p-5 transition-all duration-500 "+(p>i*.2&&p<(i+1)*.27+.2?"border-emerald-400/50 bg-[#0a2b23] text-white shadow-xl":"border-black/10 bg-white text-[#0b2922]")}><div className="flex items-start gap-4"><b className="text-[9px] text-emerald-500">{x[0]}</b><div><h3 className="font-black">{x[1]}</h3><p className="mt-2 text-xs opacity-60">{x[2]}</p></div></div></div>)}</div></div></div></section>
}

function Ring({value,label,color="#55e9a2"}:{value:number,label:string,color?:string}){return <div className="relative grid place-items-center"><svg className="h-24 w-24 -rotate-90"><circle cx="48" cy="48" r="38" fill="none" stroke="#ffffff12" strokeWidth="8"/><circle cx="48" cy="48" r="38" fill="none" stroke={color} strokeWidth="8" strokeLinecap="round" strokeDasharray={239} strokeDashoffset={239*(1-value/100)}/></svg><div className="absolute text-center"><b className="text-lg">{value}%</b><p className="text-[7px] uppercase text-slate-500">{label}</p></div></div>}
export function FleetLab(){
 const[playing,setPlaying]=useState(true),[speed,setSpeed]=useState(1),[time,setTime]=useState(36),[points,setPoints]=useState<{x:number,y:number}[]>([]),[alert,setAlert]=useState<string|null>(null),[flash,setFlash]=useState(false);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setTime(v=>(v+speed)%101),90);return()=>clearInterval(id)},[playing,speed]);
 const beep=()=>{try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=760;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}};
 const trigger=(s:string)=>{setAlert(s);setFlash(true);beep();setTimeout(()=>setFlash(false),550);setTimeout(()=>setAlert(null),4200)};
 return <section className={"relative bg-[#020d0b] px-5 py-24 text-white transition-shadow sm:px-[5vw] lg:py-32 "+(flash?"shadow-[inset_0_0_0_3px_#fb8655,inset_0_0_70px_#fb865544]":"")} id="fleet-lab">
  <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(16,185,129,.18),transparent_55%)]"/>
  {alert&&<motion.div initial={{x:80,opacity:0}} animate={{x:0,opacity:1}} className="fixed right-4 top-24 z-[80] flex max-w-sm gap-3 rounded-2xl border border-orange-400/30 bg-slate-950/80 p-4 shadow-2xl backdrop-blur-2xl"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-400/15 text-orange-300"><Bell className="h-5 w-5"/></span><div><p className="text-[9px] font-black uppercase tracking-wider text-orange-300">Live fleet alert</p><b className="mt-1 block text-sm">{alert}</b><p className="mt-1 text-[9px] text-slate-500">LG-204 · just now</p></div></motion.div>}
  <div className="relative mx-auto max-w-[1300px]"><div className="mb-12"><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-300">Interactive fleet lab</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] sm:text-7xl">Replay. Draw. Trigger. Diagnose.</h2></div>
  <div className="grid gap-4 xl:grid-cols-[1.45fr_.55fr]"><div className="overflow-hidden rounded-[28px] border border-emerald-400/20 bg-slate-900/40 shadow-[0_8px_45px_rgba(0,0,0,.5)] backdrop-blur-2xl">
   <div onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setPoints(v=>[...v,{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100}])}} className="relative h-[440px] cursor-crosshair overflow-hidden bg-[#0a211c] bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:34px_34px]">
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M-5 84 C20 78 30 34 53 49 S77 76 105 22" fill="none" stroke="#203e35" strokeWidth="5"/><path d="M-5 84 C20 78 30 34 53 49 S77 76 105 22" fill="none" stroke="#4fec9e" strokeWidth=".7" strokeDasharray="2 1"/>{points.length>1&&<polygon points={points.map(p=>p.x+","+p.y).join(" ")} fill="#10b98120" stroke="#5aefa5" strokeWidth=".5" strokeDasharray="2 1"/>}</svg>
    {points.map((p,i)=><span key={i} style={{left:p.x+"%",top:p.y+"%"}} className="absolute h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[#061512] bg-emerald-300 shadow-[0_0_14px_#10b981]"/>)}
    <div style={{offsetDistance:time+"%"}} className="absolute [offset-path:path('M_0_370_C_170_340_250_145_460_215_S_690_335_900_95')] [offset-rotate:0deg]"><span className="relative grid h-10 w-10 place-items-center rounded-full border-4 border-white bg-emerald-400 text-[#08231d] shadow-[0_0_25px_#10b981]"><span className="absolute inset-0 animate-ping rounded-full bg-emerald-400/40"/><Truck className="relative h-4 w-4"/></span></div>
    <div className="absolute left-4 top-4 flex gap-2"><span className="rounded-lg border border-white/10 bg-black/50 px-3 py-2 text-[9px] backdrop-blur-xl">Click map to draw polygon</span>{points.length>0&&<button onClick={e=>{e.stopPropagation();setPoints([])}} className="grid h-8 w-8 place-items-center rounded-lg bg-black/50 text-slate-400 hover:text-white"><Trash2 className="h-3.5 w-3"/></button>}</div>
   </div>
   <div className="border-t border-white/10 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><button onClick={()=>setPlaying(!playing)} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-emerald-400 text-[#08231d]">{playing?<Pause className="h-4 w-4" fill="currentColor"/>:<Play className="h-4 w-4" fill="currentColor"/>}</button><div className="flex-1"><input aria-label="Route timeline" type="range" value={time} onChange={e=>setTime(+e.target.value)} className="w-full accent-emerald-400"/><div className="mt-1 flex justify-between text-[8px] text-slate-500"><span>00:00</span><span className="text-orange-300">● 08:42 STOP 18m</span><span>12:00</span><span className="text-orange-300">● 17:26 92km/h</span><span>24:00</span></div></div><div className="flex rounded-lg bg-white/5 p-1">{[1,2,4].map(x=><button key={x} onClick={()=>setSpeed(x)} className={"rounded-md px-3 py-2 text-[9px] font-black "+(speed===x?"bg-emerald-400 text-[#08231d]":"text-slate-400")}>{x}×</button>)}</div></div></div>
  </div>
  <aside className="space-y-4"><div className="rounded-[24px] border border-white/10 bg-slate-900/40 p-5 backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-emerald-300">Alert simulator</p><h3 className="mt-2 text-lg font-black">Test live events</h3></div><Radio className="h-5 w-5 text-emerald-300"/></div><div className="mt-5 space-y-2">{[["Trigger speeding alert",Gauge,"LG-204 exceeded 80 km/h"],["Battery low alert",BatteryCharging,"LG-204 battery below 15%"],["Geofence breach",ShieldAlert,"Vehicle LG-204 crossed Geofence Zone A"]].map(([label,Icon,msg],i)=><button key={String(label)} onClick={()=>trigger(String(msg))} className="group flex w-full items-center gap-3 rounded-xl border border-white/[.08] bg-white/[.04] p-3 text-left text-[10px] font-bold transition hover:border-orange-400/40 hover:bg-orange-400/10"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[.06] text-slate-400 group-hover:text-orange-300"><Icon className="h-4 w-4"/></span>{String(label)}<ChevronRight className="ml-auto h-3 w-3"/></button>)}</div></div>
   <div className="rounded-[24px] border border-white/10 bg-slate-900/40 p-5 backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-emerald-300">OBD-II diagnostics</p><h3 className="mt-2 text-lg font-black">Vehicle health</h3></div><span className="flex items-center gap-2 text-[8px] font-bold text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/> LIVE</span></div><div className="mt-5 grid grid-cols-2 gap-3"><Ring value={74} label="Fuel"/><Ring value={92} label="Battery"/><Ring value={68} label="Tyres" color="#61c7ff"/><Ring value={84} label="Engine" color="#ffad62"/></div><div className="mt-4 grid grid-cols-2 gap-2 text-[9px]"><div className="rounded-lg bg-white/5 p-3"><span className="text-slate-500">ENGINE TEMP</span><b className="mt-1 block text-sm">87°C</b></div><div className="rounded-lg bg-white/5 p-3"><span className="text-slate-500">VOLTAGE</span><b className="mt-1 block text-sm">13.8V</b></div></div><div className="mt-2 flex items-center gap-2 rounded-lg border border-emerald-400/15 bg-emerald-400/5 p-3 text-[9px] text-emerald-200"><Zap className="h-4 w-4"/> No active diagnostic trouble codes</div></div>
  </aside></div></div>
 </section>
}

declare global{interface Window{webkitAudioContext:typeof AudioContext}}
